# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Security Crap
email: web-admin@securitycrap.com
description: > # this means to ignore newlines until "baseurl:"
  security crap and stuff..
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://securitycrap.com" # the base hostname & protocol for your site
downloadurl: "http://download.securitycrap.com"
twitter_username: securitycrap
github_username:  securitycrap

# Build settings
# markdown: kramdown
markdown: redcarpet
